import Head from "next/head";
import Banner from "../src/Components/Home/Banner/Banner";
import Details from "../src/Components/Home/Details/Details";
import Review from "../src/Components/Home/Review/Review";
import Skill from "../src/Components/Home/Skill/Skill";
import Social from "../src/Components/Home/Social/Social";
import TeamMembers from "../src/Components/Home/TeamMembers/TeamMembers";
import Work from "../src/Components/Home/Work/Work";

export default function Home() {

  return (
    <>
      <Head>
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
        <title>Khaled Admed Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />
      <Social />
      <Details />
      <Skill />
      <TeamMembers />
      <Work/>
      <Review />
    </>
  );
}
